###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

################################################
# Trigger the workflow on push or pull request #
# but only for the master branch               #
################################################
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.1
        env:
          # Note: pythong was removed from validation because there seemed to
          # be a problem with custom pylintrc files. If this bug is solved,
          # python linting can be activated again (obviously!)
          VALIDATE_PYTHON: false

          # When setting a single validation option, all others are set to
          # false. So re-enable all the languages sed in the project.
          VALIDATE_MD: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_DOCKER: true

